#ifndef SHOWDUINO_MOSFET_BOARD_CONFIG_H
#define SHOWDUINO_MOSFET_BOARD_CONFIG_H

#define SHOWDUINO_MOSFET_NODE_FW           "0.1.0"
#define SHOWDUINO_MOSFET_BOARD             "ESP32_MOS_X4 / 303E32NMOS4"

#define SHOWDUINO_MOSFET_OUT_COUNT         4
#define SHOWDUINO_MOSFET_OUT1_GPIO         16
#define SHOWDUINO_MOSFET_OUT2_GPIO         17
#define SHOWDUINO_MOSFET_OUT3_GPIO         26
#define SHOWDUINO_MOSFET_OUT4_GPIO         27
#define SHOWDUINO_MOSFET_STATUS_LED_GPIO   23

#define SHOWDUINO_MOSFET_GPIO_VERIFIED     0
#define SHOWDUINO_MOSFET_STATUS_LED_VERIFIED 0

#define SHOWDUINO_MOSFET_PWM_HZ            1000
#define SHOWDUINO_MOSFET_PWM_BITS          8

#define SHOWDUINO_MOSFET_DEFAULT_ID        "MOSFET-01"
#define SHOWDUINO_MOSFET_DEFAULT_NAME      "MOSFET NODE 1"

#endif
