import { ShowduinoScene } from "./sceneTypes";

export const starterScene: ShowduinoScene = {
  format: "showduino-scene",
  version: 1,
  id: "scene_chamber_intro_v1",
  name: "Chamber Intro Test",
  description: "First Showduino v1 scene: heartbeat audio, portal pixels, fire, strobe, blackout.",
  author: "Showduino",
  durationMs: 12000,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  tracks: [
    { id: "track_audio", name: "Audio", type: "audio", colour: "#38bdf8", locked: false, muted: false },
    { id: "track_pixel_1", name: "Pixel Line 1", type: "pixel", colour: "#ef4444", locked: false, muted: false },
    { id: "track_pixel_2", name: "Pixel Line 2", type: "pixel", colour: "#f97316", locked: false, muted: false },
    { id: "track_pixel_3", name: "Pixel Line 3", type: "pixel", colour: "#3b82f6", locked: false, muted: false },
    { id: "track_pixel_4", name: "Pixel Line 4", type: "pixel", colour: "#e5e7eb", locked: false, muted: false },
    { id: "track_notes", name: "Notes", type: "note", colour: "#a855f7", locked: false, muted: false },
  ],
  cues: [
    {
      id: "cue_audio_001",
      name: "Heartbeat Audio",
      type: "audio",
      trackId: "track_audio",
      startMs: 0,
      durationMs: 9000,
      enabled: true,
      notes: "Audio file should exist on Mega runtime SD card.",
      file: "001",
      volume: 85,
      action: "PLAY",
    },
    {
      id: "cue_portal_pulse",
      name: "Portal Pulse",
      type: "pixel",
      trackId: "track_pixel_1",
      startMs: 0,
      durationMs: 4000,
      enabled: true,
      notes: "Slow red pulse for machine start-up.",
      line: 1,
      effect: "PULSE",
      colour: { r: 255, g: 0, b: 0 },
      brightness: 150,
      speed: 8,
    },
    {
      id: "cue_fire_line",
      name: "Fire Build",
      type: "pixel",
      trackId: "track_pixel_2",
      startMs: 1000,
      durationMs: 6000,
      enabled: true,
      notes: "Orange fire flicker for danger build-up.",
      line: 2,
      effect: "FIRE",
      colour: { r: 255, g: 80, b: 0 },
      brightness: 180,
      speed: 40,
    },
    {
      id: "cue_blue_energy",
      name: "Blue Energy",
      type: "pixel",
      trackId: "track_pixel_3",
      startMs: 4000,
      durationMs: 3000,
      enabled: true,
      notes: "Blue pulse for time energy.",
      line: 3,
      effect: "PULSE",
      colour: { r: 0, g: 120, b: 255 },
      brightness: 200,
      speed: 5,
    },
    {
      id: "cue_white_strobe",
      name: "Impact Strobe",
      type: "pixel",
      trackId: "track_pixel_4",
      startMs: 7000,
      durationMs: 1500,
      enabled: true,
      notes: "White strobe for transition impact.",
      line: 4,
      effect: "STROBE",
      colour: { r: 255, g: 255, b: 255 },
      brightness: 255,
      speed: 220,
    },
    {
      id: "cue_blackout",
      name: "Final Blackout",
      type: "pixel",
      trackId: "track_pixel_4",
      startMs: 9500,
      durationMs: 500,
      enabled: true,
      notes: "Blackout all pixel lines.",
      line: "ALL",
      effect: "BLACKOUT",
      colour: { r: 0, g: 0, b: 0 },
      brightness: 0,
      speed: 1,
    },
    {
      id: "cue_note_001",
      name: "Operator Note",
      type: "note",
      trackId: "track_notes",
      startMs: 0,
      durationMs: 12000,
      enabled: true,
      notes: "This is the first scene creator proof. Deploy should send commands to the Mega Stage Engine.",
    },
  ],
};
